### ISSUE TITLE
自适应布局

### ISSUE THREAD

**Issue by sherlocktao** [sherlocktao/Blog#6]
总结一下两列布局和三列布局的实现方式。

## 两列布局
html 代码：
```html
<div class="layout">
  <div class="content">content</div>
  <div class="aside">aside</div>
</div>
```

### 1. flex
实现两列布局最简单的方法当然是利用 [Flex布局](http://www.ruanyifeng.com/blog/2015/07/flex-grammar.html?^%$)。

flex属性是 flex-grow，flex-shrink 和 flex-basis 的简写，默认值为0 1 auto，后两个属性可选。

- flex-grow 属性定义项目的放大比例，默认为0，即如果存在剩余空间，也不放大。当 n 个 flex 项目设置为 1 时，则这项目都占剩余空间的 1 / n
- flex-shrink 属性定义了项目的缩小比例，默认为 1。如果所有项目的 flex-shrink 属性都为 1，当空间不足时，都将等比例缩小。如果一个项目的 flex-shrink 属性为 0，其他项目都为 1，则空间不足时，前者不缩小
- flex-basis 属性定义了在分配多余空间之前，项目占据的主轴空间（main size）

```css
.content {
  flex: 1;
}
.aside {
  width: 200px;
}
```

### 2. 负margin + relative + float + padding （圣杯布局原理）
原理：利用 padding 使父元素预留一块固定宽度元素的宽度，自适应元素的宽度为 100%，再使固定宽度元素定位到 pading 的位置。

- 所有元素都向左浮动
- 设置自适应元素宽度 100%
- 设置容器 .layout 的 padding 留出空间
- 设置固定宽度元素 maring 为负的自身宽度
- 设置 right 为负的自身宽度

```css
.layout {
  padding-right: 200px;
}
.content {
  width: 100%;
  float: left;
}
.aside {
  width: 200px;
  float: left;
  margin-left: -200px;
  position: relative;
  right: -200px;
}
```

### 3. 添加标签 + float + 负margin （双飞翼原理）
使用这种方式布局需要为自适应的元素添加一个父元素。
```html
<div class="layout">
  <div class="container">
    <div class="content">content</div>
  </div>
  <div class="aside">aside</div>
</div>
```

- 所有元素都向左浮动
- 设置自适应元素的容器 .container 宽度 100%
- 设置固定宽度元素 maring 为负的自身宽度
- 设置自适应元素的 margin 留出空间

```css
.container {
  width: 100%;
  float: left;
}
.content {
  margin-right: 200px;
}
.aside {
  width: 200px;
  float: left;
  margin-left: -200px;
}
```

## 三列布局
三列布局原理其实和两列布局是一样的，这里介绍的三列布局为中间自适应，两边为固定宽度。
```html
<div class="layout">
  <div class="content">content</div>
  <div class="left">left</div>
  <div class="right">right</div>
</div>
```

### 1. flex
```css
.layout {
  display: flex;
}
.layout .content {
  flex: 1;
}
.layout .left {
  width: 200px;
}
.layout .right {
  width: 200px;
}
```

### 2. 圣杯布局
- 设置容器 layout 的 padding，为固定宽度元素预留位置
- 设置三列左浮动
- 设置自适应元素 content 宽度 100%，填充容器
- 设置固定宽的元素的 负margin 和 position，使其归位

```css
.layout {
  padding: 0 200px;
}
.layout .content {
  width: 100%;
  float: left;
}
.layout .left {
  width: 200px;
  float: left;
  margin-left: -100%;
  position: relative;
  left: -200px;
}
.layout .right {
  width: 200px;
  float: left;
  margin-left: -200px;
  position: relative;
  right: -200px;
}
```

### 3. 双飞翼
添加自适应元素容器：
```html
<div class="layout">
  <div class="container">
    <div class="content">content</div>
  </div>
  <div class="left">left</div>
  <div class="right">right</div>
</div>
```
- 设置三列左浮动
- 设置自适应元素的容器 container 宽度 100%
- 设置自适应元素 marin，预留空间
- 设置固定宽度元素的 负margin，使元素归位

```css
.layout .container {
  width: 100%;
  float: left;
}
.layout .content {
  margin: 0 200px;
}
.layout .left {
  width: 200px;
  float: left;
  margin-left: -100%;
}
.layout .right {
  width: 200px;
  float: left;
  margin-left: -200px;
}
```
